add router(v6) with placeholder pages
fe-apr23-ChatGPT-approved/product_catalog_frontend pull request #2
Opened 2023-07-30 19:19 UTC by ulositska

For now I went with an older version, LMN if I should change it to the newer one

2023-07-31 11:59 UTC, okosohor requested changes

2023-07-31 11:59 UTC, okosohor commented on package-lock.json
add only ./src

2023-07-31 11:59 UTC, okosohor commented on package.json
add only ./src

2023-07-31 11:59 UTC, okosohor commented on src/App.tsx
> +        <Route path="/phones" element={<Phones />} />
need to add cart, tablets etc.

2023-07-31 11:59 UTC, okosohor commented on src/App.tsx
> +    {/* <Header /> */}
i think mb we can use outlet

2023-07-31 11:59 UTC, okosohor commented on src/index.tsx
> +    <BrowserRouter>
for GH need hashRouter

2023-07-31 20:20 UTC, Ihor-Karpyn commented
Looks like u use a different node version, it's the reason for the huge page-lock.

2023-07-31 20:20 UTC, Ihor-Karpyn commented on package-lock.json
package-lock should be added to this pull request

2023-08-01 08:03 UTC, annholovko requested changes
add routes for tablets, accessories, cart, favourites, cart etc, and add this pages too.
see https://docs.google.com/document/d/14pL86Alwv6a1gw7iq2Qn89MiKTwFWNIfsYllQmfLfR8/edit

2023-08-01 20:50 UTC, closed without merging